### ISSUE TITLE
error when play it with es6.3

### ISSUE THREAD

**Issue by loopmocker** [aaron-horst/Kibana3-for-Elasticsearch-5-and-6#4]
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:5601' is therefore not allowed access.

elasticsearch already have below config:

```
http.cors.enabled: true
http.cors.allow-origin: "*"
```

**Comment by aaron-horst** [comment]
This is related to your ES settings rather than K3... you need to ensure it is consistent on all of your nodes so that all restful queries have the chance to succeed.
